# The "params" section includes the configuration of a single Git repository that needs to be scanned.
# For Azure Repos, Bitbucket Server and GitHub with JFrog Pipelines or Jenkins, you can define multiple "params" sections one after the other, for scanning multiple
# Git repositories in the same organization.
- params:
    # Git parameters
    git:
      # [Mandatory]
      # Name of the git repository to scan
      repoName: repo-name

      # [Mandatory]
      # List of branches to scan
      branches:
        - master

    # Frogbot scanning parameters
    scan:
      # [Optional, Default: false]
      # Frogbot displays all existing vulnerabilities, including the ones that were not added by the pull request
      # includeAllVulnerabilities: true

      # [Optional, Default: true]
      # Frogbot does not fail the task if security issues are found and this parameter is set to false
      # failOnSecurityIssues: false

      # List of subprojects / project dirs inside the Git repository
      projects:
      # [Mandatory for projects which use npm, yarn 2, nuget and dotnet to download their dependencies]
      # Installation command (e.g. npm i, nuget restore)
      # - installCommand: ""

      # [Optional, Default: root directory]
      # List of relative path's to the projects directories in the git repository
      #   workingDirs:
      #     - "."

      # [Mandatory for pip only if using requirements file, Default: pip install .]
      # The requirements file name that used to install dependencies in case of pip package manager
      #   pipRequirementsFile: ""

      # [Optional, Default: true]
      # Use Gradle Wrapper (gradlew/gradlew.bat) to run Gradle
      #   useWrapper: true

      # [Optional]
      # Name of the Artifactory Virtual Repository to resolve dependencies from
      #   depsResolutionRepo: ""

    # JFrog Platform parameters
    jfrogPlatform:
    # [Optional]
    # JFrog project key. Learn more about it [here](https://www.jfrog.com/confluence/display/JFROG/Projects)
    # jfrogProjectKey: ""

    # [Optional]
    # Xray Watches. Learn more about it [here](https://www.jfrog.com/confluence/display/JFROG/Configuring+Xray+Watches)
    # watches:
    #  - ""