# The "params" section includes the configuration of a single Git repository that needs to be scanned.
# For Azure Repos, Bitbucket Server and GitHub with JFrog Pipelines or Jenkins, you can define multiple "params" sections one after the other, for scanning multiple
# Git repositories in the same organization.
- params:
    # Git parameters
    git:
      # [Mandatory]
      # Name of the git repository to scan
      repoName: repo-name

      # [Mandatory]
      # List of branches to scan
      branches:
        - master

      # [Optional] Custom formats for commits, branches, and PR created by Frogbot.
      customFormats:
        # Please note, Frogbot will replace the following placeholders
        # 1. IMPACTED_PACKAGE
        # 2. FIX_VERSION
        # Example branchName:"(MyLabel):Vulnerability_fix_IMPACTED_PACKAGE_to_version_FIX_VERSION"

        commitTitle: ""

        pullRequestTitle: ""

        branchName: ""

    # Frogbot scanning parameters
    scan:
      # [Default: false]
      # Frogbot displays all existing vulnerabilities, including the ones that were not added by the pull request
      # includeAllVulnerabilities: true

      # [Default: true]
      # Frogbot does not fail the task if security issues are found and this parameter is set to false
      # failOnSecurityIssues: false

      # List of subprojects / project dirs inside the Git repository
      projects:
      # [Mandatory if the two conditions below are met]
      # 1. The project uses yarn 2, NuGet or .NET Core to download its dependencies
      # 2. The `installCommand` variable isn't set in your frogbot-config.yml file.
      #
      # The command that installs the project dependencies (e.g "nuget restore")
      # - installCommand: ""

      # [Default: root directory]
      # List of relative path's to the projects directories in the git repository
      #   workingDirs:
      #     - "."

      # [Mandatory for pip only if using requirements file, Default: pip install .]
      # The requirements file name that used to install dependencies in case of pip package manager
      #   pipRequirementsFile: ""

      # [Default: true]
      # Use Gradle Wrapper (gradlew/gradlew.bat) to run Gradle
      #   useWrapper: true

      # [Optional]
      # Name of a Virtual Repository in Artifactory to resolve (download) the project dependencies from
      #   repository: ""

    # JFrog Platform parameters
    jfrogPlatform:
    # [Optional]
    # JFrog project key. Learn more about it [here](https://www.jfrog.com/confluence/display/JFROG/Projects)
    # jfrogProjectKey: ""

    # [Optional]
    # Xray Watches. Learn more about it [here](https://www.jfrog.com/confluence/display/JFROG/Configuring+Xray+Watches)
    # watches:
    #  - ""
