name: "Frogbot"
on:
  pull_request_target:
    types: [labeled]
jobs:
  comment:
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build Frogbot
        run: buildscripts/build.sh

      - name: Scan Pull Request
        env:
          FROGBOT_JF_USER: ${{ secrets.FROGBOT_JF_USER }}
          FROGBOT_JF_URL: ${{ secrets.FROGBOT_JF_XRAY_URL }}
          FROGBOT_JF_XRAY_URL: ${{ secrets.FROGBOT_JF_URL }}
          FROGBOT_JF_ARTIFACTORY_URL: ${{ secrets.FROGBOT_JF_ARTIFACTORY_URL }}
          FROGBOT_JF_PASSWORD: ${{ secrets.FROGBOT_JF_PASSWORD }}
          FROGBOT_GIT_OWNER: ${{ github.repository_owner }}
          FROGBOT_GIT_REPO: ${{ github.server_url }}/${{ github.repository }}
          FROGBOT_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROGBOT_GIT_BASE_BRANCH: ${{ github.base_ref}}
          FROGBOT_PR: ${{ github.event.number }}
          JFROG_CLI_LOG_LEVEL: DEBUG
        run: ./frogbot scan-pull-request
