
name: "Frogbot"
on:
  # issue_comment triggers this action on each comment on pull requests
  pull_request_target:
    types: [labeled]
jobs:
  comment:
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build Frogbot
        run: CGO_ENABLED=0 go build -o frogbot -ldflags '-w -extldflags "-static"' main.go

      - name: Scan Pull Request
        env:
          FROGBOT_JF_USER: ${{ secrets.FROGBOT_JF_USER }}
          FROGBOT_JF_URL: ${{ secrets.FROGBOT_JF_URL }}
          FROGBOT_JF_PASSWORD: ${{ secrets.FROGBOT_JF_PASSWORD }}
          FROGBOT_GIT_OWNER: $GITHUB_REPOSITORY_OWNER
          FROGBOT_GIT_REPO: ${{ github.repository }}
          FROGBOT_GIT_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROGBOT_GIT_BASE_BRANCH: $GITHUB_BASE_REF
          FROGBOT_PR: ${{ github.event.number }}
        run: ./frogbot scan-pull-request
