name: Validate Pull Request Target Branch

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  validate-target-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check Target Branch
        run: |
          if [ "${{ github.base_ref }}" != "dev" || "${{ github.base_ref }}" != "v3_er" ]; then
            echo "Pull requests must target the 'dev' branch."
            exit 1
          fi
